version: '3.2'

networks:
  network-jenkins:

services:
  jeknins:
    build: .
    ports:
      - target: 8080
        published: 8080
      - target: 50000
        published: 50000
    volumes:
      - /home/auser/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      network-jenkins:
        aliases:
          - jenkins